if (self.CavalryLogger) { CavalryLogger.start_js(["+7aFn"]); }

__d("XCometVideoHomeLiveControllerRouteBuilder",["cometRouteBuilder"],(function(a,b,c,d,e,f){a=b("cometRouteBuilder")("/watch/live/",Object.freeze({}),void 0);e.exports=a}),null);
__d("CometGranularTimestamp.react",["fbt","CometTimestamp.react","React","formatDate","useServerTime"],(function(a,b,c,d,e,f,g){"use strict";var h=b("React"),i=1e3*60*60,j=i*24;function k(a,b){return a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate()}function a(a){var c=a.date;a=a.granularity;a=a===void 0?"none":a;var d=b("useServerTime")();if(a==="none"||a==="min")return h.jsx(b("CometTimestamp.react"),{date:c});if(a==="hour"){var e=c.valueOf()%i;e=new Date(c.valueOf()-e);return h.jsx(b("CometTimestamp.react"),{date:e})}if(a==="year")return b("formatDate")(c,"Y");if(a==="month")return d.getFullYear()===c.getFullYear()?b("formatDate")(c,"F"):b("formatDate")(c,"F Y");if(k(c,d))return g._("Today");e=new Date(d.valueOf()-j);if(k(c,e))return g._("Yesterday");a=new Date(d.valueOf()+j);if(k(c,a))return g._("Tomorrow");return d.getFullYear()!==c.getFullYear()?b("formatDate")(c,"F j, Y"):b("formatDate")(c,"F j")}e.exports=a}),null);
__d("ShowSurfacesLoggingUtil",["Banzai","WebSession"],(function(a,b,c,d,e,f){"use strict";var g="show_surfaces";a={log:function(a,c,d,e,f,h,i,j,k){b("Banzai").post(g,{entrypoint_surface:c,event:e,event_data:f,page_id:a,player_origin:j,player_suborigin:k,session_id:b("WebSession").getId(),surface:d,video_id:h,video_list_id:i})}};e.exports=a}),null);
__d("cometVideoHomeScrollTo",["VideoHomeTypedLoggerLite","gkx","scrollTo"],(function(a,b,c,d,e,f){"use strict";function c(c,d,e){c=c.getBoundingClientRect();var f=c.height;c=c.top;e=(window.innerHeight-d-e-f)/2+d;f=e-c;d=b("gkx")("1243461");b("scrollTo")({behavior:d?"auto":"smooth",left:a.pageXOffset,top:a.pageYOffset-f});b("VideoHomeTypedLoggerLite").log({event:"auto_scroll"})}e.exports=c}),null);
__d("cometVideoHomeScrollToRef",["cometVideoHomeScrollTo"],(function(a,b,c,d,e,f){"use strict";function a(a,c,d){if(a==null)return;a=a.current;if(a==null)return;b("cometVideoHomeScrollTo")(a,c,d)}e.exports=a}),null);
__d("VideoPlayerWithAutoCenterOnUserInitiatedPlay.react",["CometViewportMarginsContext","React","VideoPlayerHooks","cometVideoHomeScrollToRef","stylex","usePrevious"],(function(a,b,c,d,e,f){"use strict";var g=b("React");c=b("React");var h=c.useContext,i=c.useEffect,j=c.useRef,k=b("VideoPlayerHooks").useLastPlayReason,l=b("VideoPlayerHooks").usePaused;function a(){var a=j(null),c=l(),d=b("usePrevious")(c),e=k(),f=h(b("CometViewportMarginsContext")),m=f.bottom,n=f.top;i(function(){d===!0&&c===!1&&e==="user_initiated"&&b("cometVideoHomeScrollToRef")(a,n,m)},[e,c,d,m,n]);return g.jsx("div",{className:"kr520xx4 j9ispegn pmk7jnqg hzruof5a n7fi1qx3 i09qtzwb",ref:a})}e.exports=a}),null);
__d("CometVideoHomeFeedAutoAdvanceAPIContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({advance:function(){},register:function(){},unregister:function(){}});e.exports=c}),null);
__d("CometVideoHomeFeedUnitPositionContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(0);e.exports=c}),null);
__d("VideoPlayerWithVideoHomeAutoAdvance.react",["CometVideoHomeFeedAutoAdvanceAPIContext","CometVideoHomeFeedUnitPositionContext","React","VideoPlayerHooks","usePrevious"],(function(a,b,c,d,e,f){"use strict";b("React");c=b("React");var g=c.useContext,h=c.useEffect,i=b("VideoPlayerHooks").useEnded;function a(){var a=i(),c=b("usePrevious")(a),d=g(b("CometVideoHomeFeedAutoAdvanceAPIContext")),e=g(b("CometVideoHomeFeedUnitPositionContext"));h(function(){c===!1&&a===!0&&d.advance(e)},[d,a,e,c]);return null}e.exports=a}),null);
__d("CometLiveCommentReplyContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({replyCommentID:null,replyingToHeader:null,setReplyingToHeader:function(){}});e.exports={CometLiveCommentReplyContext:c}}),null);
__d("CometTahoeUFIContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c={COMPOSER_AND_ALL_COMMENTS:"COMPOSER_AND_ALL_COMMENTS",COMPOSER_AND_TOP_COMMENT:"COMPOSER_AND_TOP_COMMENT",COMPOSER_ONLY:"COMPOSER_ONLY"};d=a.createContext({tahoeCommentComposerConfig:c.COMPOSER_AND_ALL_COMMENTS});e.exports={CometTahoeUFIContext:d,TahoeCommentComposerConfigEnum:c}}),null);
__d("VideoHomeCometErrorBoundary.react",["CometErrorBoundary.react","React","VideoHomeTypedLoggerLite"],(function(a,b,c,d,e,f){"use strict";var g=b("React");c=b("React");var h=c.useCallback;function a(a){var c=h(function(c){b("VideoHomeTypedLoggerLite").log({event:"js_error",exception:c.message,exception_trace:c.componentStack,module_class:a.moduleClass,unit_position:a.unitPosition})},[a.moduleClass,a.unitPosition]);return g.jsx(b("CometErrorBoundary.react"),{context:{project:"www_watch"},fallback:a.fallback,onError:c,children:a.children})}e.exports=a}),null);
__d("CometVideoProfileInfoGlimmer.react",["BaseGlimmer.react","React","stylex"],(function(a,b,c,d,e,f){"use strict";var g=b("React");function a(a){var c;a=a.index;return g.jsxs("div",{className:"cbu4d94t j83agx80",children:[g.jsxs("div",{className:"j83agx80",children:[g.jsx(c=b("BaseGlimmer.react"),{className:"go5t5npl oi9244e8 hxdsxuhi spb7xbtv bkmhp75w emlxlaya s45kfl79",index:a}),g.jsxs("div",{className:"taijpn5t cbu4d94t j83agx80",children:[g.jsx(c,{className:"elpiyq4v bi6gxh9e cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:a}),g.jsx(c,{className:"i7o4yfgj cyypbtt7 kzx2olss aot14ch1 p86d2i9g beltcj47",index:a})]})]}),g.jsx(c,{className:"f4c7eilb n1l5q3vz jnigpg78 ns4ygwem fykbt5ly hgaippwi fni8adji",index:a})]})}e.exports=a}),null);
__d("CometVideoHomeThreeDotContextMenuWrapperContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");e.exports=a.createContext({contextMenuEnabled:null})}),null);
__d("CometVideoHomeFunnelLoggingContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({hasPermalinkInjection:!1});e.exports=c}),null);
__d("CometVideoHomeRootContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({autoplay:!0,autoplaySettingsPromptVisitNum:0,injectedVideoID:null,isFacebookReferrer:!1,lastFeedVisitTime:0,qplInstanceKey:0});e.exports=c}),null);
__d("CometVideoHomeSectionPositionContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("CometVideoHomeShowSurfacesLoggingContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({entrypoint:"",pageID:null,sectionTypeName:"",surface:""});e.exports=c}),null);
__d("VideoHomeGlobalSoundContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext({muted:!0,setMuted:function(){},setVolume:function(){},volume:1});e.exports=c}),null);
__d("CometVideoHomeLiveTabExperiments",["gkx","qex"],(function(a,b,c,d,e,f){"use strict";a=function(){return b("gkx")("1429886")||b("gkx")("976093")&&b("gkx")("1351276")};var g=function(){return!0},h=function(){return b("gkx")("1205329")||b("gkx")("976093")&&b("gkx")("1399700")},i=function(){return!0};c=function(){return!!b("qex")._("1441558")};e.exports={dedupEnabled:function(){return!0},hotswapEnabled:a,injectionEnabled:g,isFeaturedLiveBeforeTopLives:c,liveEnabled:h,thumbnailsInjectEnabled:function(){return!i()&&g()&&h()}}}),null);
__d("VideoHomeLoggingExternalLogIDContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("VideoHomeLoggingReactionVideoChannelTypeContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("VideoHomeLoggingUpstreamPlayerSourceContext",["React"],(function(a,b,c,d,e,f){"use strict";a=b("React");c=a.createContext(null);e.exports=c}),null);
__d("logVideoHomeWebFunnel",["CurrentUser","WebFunnelLogger","gkx"],(function(a,b,c,d,e,f){"use strict";function a(a,c,d,e){if(!b("gkx")("1238150"))return;var f=new(b("WebFunnelLogger"))("VideoHomeWWWFunnelDefinition").setAction(a).setSessionKey(b("CurrentUser").getID());c!=null&&Object.entries(c).forEach(function(a){var b=a[0];a=a[1];f.addFunnelPayload(b,a)});d!=null&&Object.entries(d).forEach(function(a){var b=a[0];a=a[1];f.addActionPayload(b,a)});e&&f.markStart();f.log()}e.exports=a}),null);